// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByigaovLz-2n3PKJqIjiXVUnhbD8qBUN0',
    appId: '1:1032905455324:web:01331e4976d5984abb6619',
    messagingSenderId: '1032905455324',
    projectId: 'changaya-dev',
    authDomain: 'changaya-dev.firebaseapp.com',
    storageBucket: 'changaya-dev.firebasestorage.app',
    measurementId: 'G-Y8B3WZ8YQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYtZ_2Q2-gNd2juDfceD5Nm0shGR7py0',
    appId: '1:1032905455324:android:a86b3d4d0a69c885bb6619',
    messagingSenderId: '1032905455324',
    projectId: 'changaya-dev',
    storageBucket: 'changaya-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEYAaTS36oZATOMbMYe5kA2dqgmOOac8',
    appId: '1:1032905455324:ios:b9d57bfc640e5c46bb6619',
    messagingSenderId: '1032905455324',
    projectId: 'changaya-dev',
    storageBucket: 'changaya-dev.firebasestorage.app',
    iosClientId: '1032905455324-b2pcaan0mh1sce9j8th3tmmpeuan4ve3.apps.googleusercontent.com',
    iosBundleId: 'com.changaya.app',
  );
}
